package com.gaurav145.myweather.model.locationData

data class LocalNames(
    val ar: String,
    val be: String,
    val bg: String,
    val bn: String,
    val de: String,
    val el: String,
    val en: String,
    val es: String,
    val fa: String,
    val gu: String,
    val he: String,
    val hi: String,
    val hy: String,
    val ja: String,
    val kk: String,
    val kn: String,
    val ko: String,
    val ml: String,
    val mr: String,
    val oc: String,
    val or: String,
    val pa: String,
    val ps: String,
    val ru: String,
    val sd: String,
    val sr: String,
    val ta: String,
    val te: String,
    val uk: String,
    val ur: String,
    val zh: String
)